# Generated by Django 3.2.9 on 2021-11-22 12:25

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):
    """ Migration class """

    dependencies = [
        ('checkout', '0002_auto_20211122_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
